### ISSUE TITLE
Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by sergeygross** [KexianHust/Structure-Guided-Ranking-Loss#6]
Hello,
 I have next issue after dealing with preparations and model.pth.tar download:

```
Traceback (most recent call last):
  File "demo.py", line 89, in <module>
    net.load_state_dict(checkpoint['state_dict'])
  File "/home/grid/Dev/anaconda3/envs/structure_guided_loss/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.encoder.bn1.num_batches_tracked", "module.encoder.layer1.0.bn1.num_batches_tracked", "module.encoder.layer1.0.bn2.num_batches_tracked", "module.encoder.layer1.0.bn3.num_batches_tracked", "module.encoder.layer1.0.downsample.1.num_batches_tracked", "module.encoder.layer1.1.bn1.num_batches_tracked", "module.encoder.layer1.1.bn2.num_batches_tracked", "module.encoder.layer1.1.bn3.num_batches_tracked", "module.encoder.layer1.2.bn1.num_batches_tracked", "module.encoder.layer1.2.bn2.num_batches_tracked", "module.encoder.layer1.2.bn3.num_batches_tracked", "module.encoder.layer2.0.bn1.num_batches_tracked", "module.encoder.layer2.0.bn2.num_batches_tracked", "module.encoder.layer2.0.bn3.num_batches_tracked", "module.encoder.layer2.0.downsample.1.num_batches_tracked", "module.encoder.layer2.1.bn1.num_batches_tracked", "module.encoder.layer2.1.bn2.num_batches_tracked", "module.encoder.layer2.1.bn3.num_batches_tracked", "module.encoder.layer2.2.bn1.num_batches_tracked", "module.encoder.layer2.2.bn2.num_batches_tracked", "module.encoder.layer2.2.bn3.num_batches_tracked", "module.encoder.layer2.3.bn1.num_batches_tracked", "module.encoder.layer2.3.bn2.num_batches_tracked", "module.encoder.layer2.3.bn3.num_batches_tracked", "module.encoder.layer3.0.bn1.num_batches_tracked", "module.encoder.layer3.0.bn2.num_batches_tracked", "module.encoder.layer3.0.bn3.num_batches_tracked", "module.encoder.layer3.0.downsample.1.num_batches_tracked", "module.encoder.layer3.1.bn1.num_batches_tracked", "module.encoder.layer3.1.bn2.num_batches_tracked", "module.encoder.layer3.1.bn3.num_batches_tracked", "module.encoder.layer3.2.bn1.num_batches_tracked", "module.encoder.layer3.2.bn2.num_batches_tracked", "module.encoder.layer3.2.bn3.num_batches_tracked", "module.encoder.layer3.3.bn1.num_batches_tracked", "module.encoder.layer3.3.bn2.num_batches_tracked", "module.encoder.layer3.3.bn3.num_batches_tracked", "module.encoder.layer3.4.bn1.num_batches_tracked", "module.encoder.layer3.4.bn2.num_batches_tracked", "module.encoder.layer3.4.bn3.num_batches_tracked", "module.encoder.layer3.5.bn1.num_batches_tracked", "module.encoder.layer3.5.bn2.num_batches_tracked", "module.encoder.layer3.5.bn3.num_batches_tracked", "module.encoder.layer4.0.bn1.num_batches_tracked", "module.encoder.layer4.0.bn2.num_batches_tracked", "module.encoder.layer4.0.bn3.num_batches_tracked", "module.encoder.layer4.0.downsample.1.num_batches_tracked", "module.encoder.layer4.1.bn1.num_batches_tracked", "module.encoder.layer4.1.bn2.num_batches_tracked", "module.encoder.layer4.1.bn3.num_batches_tracked", "module.encoder.layer4.2.bn1.num_batches_tracked", "module.encoder.layer4.2.bn2.num_batches_tracked", "module.encoder.layer4.2.bn3.num_batches_tracked", "module.decoder.conv.conv_branch.2.num_batches_tracked", "module.decoder.ffm2.ftb1.conv_branch.2.num_batches_tracked", "module.decoder.ffm2.ftb2.conv_branch.2.num_batches_tracked", "module.decoder.ffm1.ftb1.conv_branch.2.num_batches_tracked", "module.decoder.ffm1.ftb2.conv_branch.2.num_batches_tracked", "module.decoder.ffm0.ftb1.conv_branch.2.num_batches_tracked", "module.decoder.ffm0.ftb2.conv_branch.2.num_batches_tracked", "module.decoder.outconv.adapt_conv.1.num_batches_tracked". 
```

**Comment by sergeygross** [comment]
answer is changing pytorch from 0.4 to 0.4.1
